namespace Rakr.Application.Jobs.Dtos;

public record JobDetailDto(
    Guid Id,
    string Title,
    string Description,
    string[] Categories,
    string Address,
    double Latitude,
    double Longitude,
    string Status,
    int BudgetCents,
    DateTime? ScheduleStart,
    DateTime? ScheduleEnd,
    string[]? Photos,
    DateTime CreatedAt,
    Guid CustomerProfileId,
    int PendingRequestCount = 0,
    string? AssignedVendorName = null,
    Guid? AssignedVendorUserId = null,
    bool IsRecurring = false,
    string? RecurringFrequency = null,
    string[]? RecurringDays = null,
    string? RecurringTime = null,
    string PricingType = "fixed",
    int? HourlyRateCents = null,
    decimal? EstimatedHours = null,
    decimal? MaxHours = null,
    DateTime? AssignmentStartedAt = null,
    DateTime? AssignmentCompletedAt = null,
    string? JobDetailsJson = null
);
